# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statscollect_scrap', '0003_processedgame_processedgamerating_processedgamesheetplayer_processedgamesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedgamerating',
            name='scraped_ratio',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='processedgamerating',
            name='rating_source',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='statscollect_db.RatingSource'),
        ),
        migrations.AlterField(
            model_name='processedgamesheetplayer',
            name='scraped_ratio',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
