# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statscollect_scrap', '0003_auto_20170413_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedratingsource',
            name='rating_source',
            field=models.ManyToManyField(related_name='expected_set', to='statscollect_db.RatingSource'),
        ),
        migrations.AlterField(
            model_name='processedgameratingsource',
            name='rating_ds',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='statscollect_scrap.ScrapedDataSheet'),
        ),
        migrations.AlterField(
            model_name='processedgameratingsource',
            name='rating_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statscollect_db.RatingSource'),
        ),
        migrations.AlterField(
            model_name='processedgamesummary',
            name='processed_game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_summary', to='statscollect_scrap.ProcessedGame'),
        ),
    ]
