# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-30 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statscollect_scrap', '0005_auto_20170429_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedgamerating',
            name='rating_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statscollect_db.RatingSource'),
        ),
        migrations.AlterField(
            model_name='processedgamerating',
            name='scraped_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
