# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-30 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statscollect_db', '__first__'),
        ('statscollect_scrap', '0006_auto_20170430_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedgamesheetplayer',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='statscollect_db.Team'),
            preserve_default=False,
        ),
    ]
