# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-04 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statscollect_scrap', '0010_scrapedteamwithplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedgame',
            name='gamesheet_ds',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gamesheet_processedgame', to='statscollect_scrap.ScrapedDataSheet'),
        ),
    ]
