# Generated by Django 2.2.27 on 2022-03-08 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statscollect_db', '0006_auto_20180822_1059'),
        ('statscollect_scrap', '0011_auto_20200204_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrappedTournamentInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_instance', models.ForeignKey(blank=True, help_text='Edition de cette compétition', null=True, on_delete=django.db.models.deletion.SET_NULL, to='statscollect_db.TournamentInstance')),
                ('actual_tournament', models.ForeignKey(blank=True, help_text='Championnat ou compétition', null=True, on_delete=django.db.models.deletion.SET_NULL, to='statscollect_db.Tournament')),
            ],
        ),
    ]
