# Generated by Django 2.2.27 on 2022-03-08 10:56

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('statscollect_scrap', '0012_scrappedtournamentinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappedtournamentinstance',
            name='actual_instance',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='actual_tournament', chained_model_field='actual_tournament', null=True, on_delete=django.db.models.deletion.SET_NULL, to='statscollect_db.TournamentInstance'),
        ),
    ]
