# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statscollect_db', '0002_footballpersonalstats_penalties_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='tournamentinstance',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='tournamentinstancestep',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
