# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-15 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statscollect_db', '0004_auto_20180613_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativePersonName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_name', models.CharField(max_length=127)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='native_name',
        ),
        migrations.AddField(
            model_name='alternativepersonname',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_names', to='statscollect_db.Person'),
        ),
    ]
