# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-22 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statscollect_db', '0005_auto_20180615_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingsource',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ratingsource',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ratingsource',
            name='uuid',
        ),
    ]
